# Generated by Django 4.2.5 on 2023-10-24 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='availability',
            field=models.CharField(default=100, max_length=300),
            preserve_default=False,
        ),
    ]
