# Generated by Django 4.2.5 on 2023-11-02 01:17

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='availability',
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), size=7)),
                ('end_time', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), size=7)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), size=7)),
                ('end_time', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), size=7)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
